// Code generated by go2go; DO NOT EDIT.


//line math.go2:1
package math

//line math.go2:1
import (
//line math.go2:1
 "math"
//line math.go2:1
 "testing"
//line math.go2:1
)

//line math.go2:1
type Importable୦ int

//line math.go2:1
var _ = math.Abs
//line math.go2:1
var _ = testing.AllocsPerRun
